# -------------------------------------------------------------------------------------
#
# Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

{{- if .Values.wso2.deployment.statefulSet.enabled }}
# Governing service of the API Manager StatefulSet (gives each pod a stable DNS identity)
apiVersion: v1
kind: Service
metadata:
  name: {{ template "am-all-in-one.fullname" . }}-am-headless
  namespace : {{ .Release.Namespace }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    deployment: {{ template "am-all-in-one.fullname" . }}-am
  ports:
    - name: jms-tcp
      protocol: TCP
      port: {{ add 5672 (.Values.wso2.apim.portOffset | default 0) }}
{{- end }}
